package com.example.llmapp.core.memory

import android.util.Log
import com.example.llmapp.core.database.MemoryDao
import com.example.llmapp.core.orchestrator.MemoryType
import com.example.llmapp.core.orchestrator.RetrievedMemory
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/**
 * Cost-budgeted multi-store memory retrieval.
 * Processes stores cheapest-first (PROFILE → SEMANTIC → EPISODIC)
 * and skips stores that exceed the remaining cost budget.
 */
class MemoryRetriever(private val dao: MemoryDao) {

    companion object {
        private const val TAG = "MemoryRetriever"
    }

    /**
     * Retrieves memories from requested categories, respecting cost budget.
     * @param searchTerms Keywords generated by MemoryPlanner
     * @param categories Which stores to search
     * @param budget Max total results across all stores
     * @param costBudget Max total recall cost
     */
    suspend fun retrieve(
        searchTerms: List<String>,
        categories: Set<MemoryType>,
        budget: Int,
        costBudget: Int
    ): List<RetrievedMemory> = withContext(Dispatchers.IO) {
        val results = mutableListOf<RetrievedMemory>()
        var remainingCost = costBudget
        val perCategoryLimit = (budget / categories.size.coerceAtLeast(1)).coerceAtLeast(2)

        // Process cheapest stores first
        val orderedCategories = categories.sortedBy { it.recallCost }

        for (category in orderedCategories) {
            if (remainingCost < category.recallCost) {
                Log.d(TAG, "Skipping $category (cost=${category.recallCost} > remaining=$remainingCost)")
                continue
            }
            remainingCost -= category.recallCost

            when (category) {
                MemoryType.PROFILE -> {
                    val profiles = if (searchTerms.isNotEmpty()) {
                        searchTerms.flatMap { dao.searchProfiles(it) }.distinctBy { it.id }
                    } else {
                        dao.getActiveProfiles()
                    }.take(perCategoryLimit)

                    Log.d(TAG, "PROFILE: ${profiles.size} results")
                    results += profiles.map { p ->
                        RetrievedMemory(
                            id = p.id,
                            content = "${p.key}: ${p.value}",
                            sourceType = MemoryType.PROFILE,
                            trustZone = 1, // User-explicit data
                            importanceScore = p.importanceScore,
                            epistemicState = p.epistemicState,
                            accessCount = p.accessCount,
                            timestamp = p.validFrom,
                            lineageId = p.lineageId
                        )
                    }
                }

                MemoryType.SEMANTIC -> {
                    val ftsQuery = searchTerms.joinToString(" OR ")
                    val semantics = if (ftsQuery.isNotBlank()) {
                        try {
                            dao.searchSemanticFts(ftsQuery, perCategoryLimit)
                        } catch (e: Exception) {
                            Log.w(TAG, "FTS search failed: ${e.message}")
                            dao.getRecentSemantic(perCategoryLimit)
                        }
                    } else {
                        dao.getRecentSemantic(perCategoryLimit)
                    }

                    Log.d(TAG, "SEMANTIC: ${semantics.size} results")
                    results += semantics.map { s ->
                        RetrievedMemory(
                            id = s.id,
                            content = s.content,
                            sourceType = MemoryType.SEMANTIC,
                            trustZone = 2, // Agent-inferred
                            importanceScore = s.importanceScore,
                            epistemicState = s.epistemicState,
                            accessCount = s.accessCount,
                            timestamp = s.timestamp,
                            lineageId = s.lineageId
                        )
                    }
                }

                MemoryType.EPISODIC -> {
                    val episodes = if (searchTerms.isNotEmpty()) {
                        searchTerms.flatMap { dao.searchEpisodes(it, perCategoryLimit) }
                            .distinctBy { it.id }
                    } else {
                        dao.getRecentEpisodes(perCategoryLimit)
                    }.take(perCategoryLimit)

                    Log.d(TAG, "EPISODIC: ${episodes.size} results")
                    results += episodes.map { e ->
                        RetrievedMemory(
                            id = e.id,
                            content = "Episode: ${e.topic} — ${e.outcome}",
                            sourceType = MemoryType.EPISODIC,
                            trustZone = 2,
                            importanceScore = 0.6f, // Episodes are moderately important
                            epistemicState = "VERIFIED", // Summaries are ground truth
                            accessCount = 1,
                            timestamp = e.timestamp,
                            lineageId = e.sessionId
                        )
                    }
                }
            }
        }

        Log.d(TAG, "Total retrieved: ${results.size} from ${orderedCategories.map { it.name }}")
        results
    }

    /**
     * Updates access counts for retrieved memories (called after successful recall).
     */
    suspend fun trackAccess(memories: List<com.example.llmapp.core.orchestrator.RankedMemory>) = withContext(Dispatchers.IO) {
        val profileIds = memories.filter { it.sourceType == MemoryType.PROFILE }.map { it.sourceId }
        val semanticIds = memories.filter { it.sourceType == MemoryType.SEMANTIC }.map { it.sourceId }

        if (profileIds.isNotEmpty()) dao.batchUpdateProfileAccess(profileIds)
        if (semanticIds.isNotEmpty()) dao.batchUpdateSemanticAccess(semanticIds)
    }
}
